main/project/api_app/urls.py
from django.conf.urls import url
from django.urls import path
from api_app import views

urlpatterns = [
    url(r'authenticate_user$', views.authenticate_user, name="authenticate_user"),
    url(r'api/create_crawl', views.api_create_crawl, name="api_create_crawl"),
    url(r'api/crawl_contents', views.api_crawl_contents, name="api_crawl_contents"),
    url(r'api/get_job_status', views.get_api_job_status, name="api_job_status")
]

main/project/main_app/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views

urlpatterns = [
    url(r'home$', views.home, name="mainapp_home"),
    url(r'new_job$', views.new_job, name="mainapp_new_job"),
    path(r'job/<int:job_id>', views.job_details, name="mainapp_jobdetails"),
    path(r'contents/<int:job_id>', views.crawl_contents, name="mainapp_crawlcontents"),
    url(r'login$', LoginView.as_view(template_name="main_app/login_form.html"), name="mainapp_login"),
    url(r'logout$', LogoutView.as_view(), name="mainapp_logout"),
    url(r'api/register_crawler_manager$', views.register_crawler_manager, name="api_register_crawler_manager"),
    url(r'api/crawl_complete$', views.complete_crawl, name="api_complete_crawl"),
    url(r'api/ping$', views.api_ping, name="api_ping"),
    url(r'ml_models$', views.ml_model, name="mainapp_mlmodel"),
]

main/project/webcrawler/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path

from .views import welcome

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main_app/', include('main_app.urls')),
    url(r'^api_app/', include('api_app.urls')),
    url(r'^.*$', welcome, name="webcrawler_welcome"),
]

main/project/main_app/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class MlModel(models.Model):
    """
    The model to represent the user Machine Learning Models.
    """
    name = models.CharField(max_length=128)
    labels = models.TextField(default='', max_length=100, blank=True)
    created = models.DateTimeField("model creation time", editable=False)
    modified = models.DateTimeField("model modification time")
    storage_location = models.URLField(default='', max_length=1000, blank=True)
    user = models.ForeignKey(User, related_name="ml_models_user", on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        """ Update created and modified timestamps whenever settings are saved """
        # only in the beginning (when the object doesn't exist yet) set the creation time.
        if not self.id:
            self.created = timezone.now()
        # set modified whenever an instance is saved
        self.modified = timezone.now()
        return super(MlModel, self).save(*args, **kwargs)

    def __str__(self):
        """
        String for representing a MlModel.
        """
        return f'{self.id} {self.name}'


class CrawlRequest(models.Model):
    """
    The model to represent a crawl request.
    """
    CRAWLTYPES = (
        (1, 'All content from a single domain'),
        (2, 'Content from multiple URLs')
    )
    STATUS = (
        (1, 'Created'),
        (2, 'In progress'),
        (3, 'Finished'),
        (4, 'Failed')
    )
    CRAWL_LIBRARY_TYPES = (
        (1, 'Selenium'),
        (2, 'Python Library')
    )
    name = models.CharField(max_length=128)
    type = models.PositiveSmallIntegerField("crawl type", default=1, choices=CRAWLTYPES)
    domain = models.URLField(default='', max_length=500, blank=True)
    urls = models.TextField(default='', max_length=1000, blank=True)
    description = models.TextField(default='', max_length=1000, blank=True)
    docs_all = models.BooleanField(default=False, blank=True)
    docs_html = models.BooleanField(default=False, blank=True)
    docs_docx = models.BooleanField(default=False, blank=True)
    docs_pdf = models.BooleanField(default=False, blank=True)
    docs_xml = models.BooleanField(default=False, blank=True)
    docs_txt = models.BooleanField(default=False, blank=True)
    docs_collected = models.PositiveIntegerField(default=0, blank=True)
    status = models.PositiveSmallIntegerField("crawl status", default=1, choices=STATUS)
    storage_location = models.URLField(default='', max_length=1000, blank=True)
    crawler_manager_endpoint = models.URLField(default='', max_length=500, blank=True)
    manifest = models.URLField(default='', max_length=1000, blank=True)
    num_crawlers = models.PositiveIntegerField("Number crawler instances", default=1)
    # maybe we want to use keywords after we receive the crawl results for better search and sorting?
    #keywords = models.ManyToManyField(Keyword, help_text="Select a keyword for this resource", blank=True)
    user = models.ForeignKey(User, related_name="crawl_requests_user", on_delete=models.CASCADE)
    created = models.DateTimeField("crawl request creation time", editable=False)
    modified = models.DateTimeField("crawl request modification time")
    model = models.ForeignKey(MlModel, default='', related_name="crawl_requests_model", on_delete=models.CASCADE, blank=True, null=True)
    model_labels = models.CharField(max_length=128, blank=True)
    crawl_library = models.PositiveSmallIntegerField("crawl library", default=1, choices=CRAWL_LIBRARY_TYPES)
    docs_uploaded = models.PositiveIntegerField(default=0, blank=True)
    num_crawl_pages_limit = models.PositiveIntegerField(default=100, blank=True)
    crawl_time = models.PositiveIntegerField(default=0, blank=True)

    def save(self, *args, **kwargs):
        """ Update created and modified timestamps whenever a Crawl Request is saved """
        # only in the beginning (when the object doesn't exist yet) set the creation time.
        if not self.id:
            self.created = timezone.now()
        # set modified whenever an instance is saved
        self.modified = timezone.now()
        return super(CrawlRequest, self).save(*args, **kwargs)

    def get_absolute_url(self):
        """
        Returns the url to access a particular crawl request instance.
        Example: "crawl_request/3"
        """
        return reverse('mainapp_jobdetails', args=[str(self.id)])

    def __str__(self):
        """
        String for representing a Crawl Request.
        """
        return f'{self.id} {self.name}'


class Profile(models.Model):
    """
    The model to represent the user settings.
    """
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)
    storage_bucket = models.URLField("Storage Bucket", default='', max_length=500, blank=True)
    api_key = models.CharField("API Key", max_length=512)
    api_secret = models.CharField("API Secret", max_length=512)
    num_crawlers = models.PositiveIntegerField("Number crawler instances", default=1)
    created = models.DateTimeField("profile creation time", editable=False)
    modified = models.DateTimeField("profile modification time")

    def save(self, *args, **kwargs):
        """ Update created and modified timestamps whenever settings are saved """
        # only in the beginning (when the object doesn't exist yet) set the creation time.
        if not self.id:
            self.created = timezone.now()
        # set modified whenever an instance is saved
        self.modified = timezone.now()
        return super(Profile, self).save(*args, **kwargs)

    def __str__(self):
        """
        String for representing a Profile.
        """
        return f'{self.id} {self.user.username}'

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        """ This method creates a profile instance as soon as a new user is created """
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        """ This method saves that profile instance to the database """
        instance.profile.save()

main/project/main_app/forms.py
from django.forms import ModelForm, HiddenInput
from .models import CrawlRequest, Profile, MlModel

class CrawlRequestForm(ModelForm):
    """ Form to hold the Crawl Request data """
    class Meta:
        model = CrawlRequest
        fields = ('name', 'type', 'domain', 'urls', 'description', 'docs_all', 'docs_html', 'docs_docx',
                  'docs_pdf', 'num_crawlers', 'model', 'model_labels', 'crawl_library', 'num_crawl_pages_limit')
        labels = {
            'name': 'Job Name',
            'type': 'Crawl Type',
            'domain': 'Domain',
            'urls': 'URLs to crawl',
            'description': 'Description',
            'docs_all': 'Collect everything',
            'docs_html': 'Collect HTML files',
            'docs_docx': 'Collect DOCX files',
            'docs_pdf': 'Collect PDF files',
            'num_crawlers': 'Number of crawler instances',
            'model' : 'Model Name',
            'model_labels' : 'Model Classification Labels',
            'crawl_library' : 'Crawl Library',
            'num_crawl_pages_limit' : 'Num Crawl Pages Limit',
        }
        widgets = {
            'user': HiddenInput(),
            'created': HiddenInput(),
            'modified': HiddenInput(),
            'docs_collected': HiddenInput(),
            'status': HiddenInput(),
            'docs_uploaded': HiddenInput(),
            'crawl_time': HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        """ Instantiates an object of type CrawlRequestForm with custom widget attributes """
        super(CrawlRequestForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Crawl Job Name'})
        self.fields['type'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Crawl Type'})
        self.fields['domain'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Domain'})
        self.fields['urls'].widget.attrs.update({'class': 'form-control', 'placeholder': 'URLs to crawl'})
        self.fields['description'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Crawl Notes'})
        self.fields['docs_all'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Collect everything'})
        self.fields['docs_html'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Collect HTML files'})
        self.fields['docs_docx'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Collect DOCX files'})
        self.fields['docs_pdf'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Collect PDF files'})
        self.fields['num_crawlers'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Number crawler instances'})
        self.fields['model'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Model Name'})
        self.fields['model_labels'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Model Classification Labels'})
        self.fields['crawl_library'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Crawl Library'})
        self.fields['num_crawl_pages_limit'].widget.attrs.update({'class': 'form-control', 'placeholder': 'num_crawl_pages_limit'})



class ProfileForm(ModelForm):
    """ Form to hold a user's profile data """
    class Meta:
        """ The meta class to set several important parameters for the form """
        model = Profile
        fields = ['storage_bucket', 'api_key', 'api_secret', 'num_crawlers']
        labels = {
            'storage_bucket': 'Enter storage URL',
            'api_key': 'storage API Key',
            'api_secret': 'Secret',
            'num_crawlers': 'Number of crawlers',
        }
        widgets = {
            'user': HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        """ Instantiates an object of type ProfileForm with custom widget attributes """
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['storage_bucket'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Enter storage URL'})
        self.fields['api_key'].widget.attrs.update({'class': 'form-control', 'placeholder': 'storage API Key'})
        self.fields['api_secret'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Secret'})
        self.fields['num_crawlers'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Number of concurrent crawler instances'})

class MlModelForm(ModelForm):
    """ Form to hold a ml_model's data """
    class Meta:
        """ The meta class to set several important parameters for the form """
        model = MlModel
        fields = ['name', 'labels']
        labels = {
            'name': 'Enter Model Name',
            'labels': 'Enter Model Labels',
        }
        widgets = {
            'user': HiddenInput(),
            'created': HiddenInput(),
            'modified': HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        """ Instantiates an object of type MlModelForm with custom widget attributes """
        super(MlModelForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Enter Model'})
        self.fields['labels'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Enter Model Labels'})

main/project/templates/main_app/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    User: {{ user.username }}
{% endblock %}

{% block content %}
    <h2 class="text-primary">Hello {{ user.username }}</h2>

    <div class="row">
         <ul class="nav nav-tabs">
             <li class="active"><a href="{% url 'mainapp_home' %}">Current Jobs</a></li>
             <li><a href="{% url 'mainapp_new_job' %}">New Job</a></li>
             <li><a href="{% url 'mainapp_mlmodel' %}">Models</a></li>
        </ul>

        <div class="tab-content">
            <div id="jobs" class="tab-pane fade in active">
                <h3>Jobs</h3>
                <p>These are all the current jobs for user {{ user.username }}. Click on a crawl job for details.</p>
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Crawl Type</th>
                            <th>Status</th>
                            <th>Job date</th>
                            <th>Docs crawled</th>
                            <th>Docs stored</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for job in jobs %}
                        <tr class="table-row" data-href="{% url 'mainapp_jobdetails' job_id=job.id %}">
                            <td>
                                {{ job.name|escape }}
                            </td>
                            <td>
                                {{ job.get_type_display|escape }}
                            </td>
                            <td>
                                {{ job.get_status_display|escape }}
                            </td>
                            <td>
                                {{ job.created|escape }}
                            </td>
                            <td>
                                {{ job.docs_collected|escape }}
                            </td>
                            <td>
                                {{ job.docs_uploaded|escape }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

main/project/templates/main_app/job_details.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    User: {{ user.username }}
{% endblock %}

{% block content %}
    <h2 class="text-primary">Hello {{ user.username }}</h2>

    <div class="row">
         <ul class="nav nav-tabs">
             <li class="active"><a href="{% url 'mainapp_home' %}">Current Jobs</a></li>
             <li><a href="{% url 'mainapp_new_job' %}">New Job</a></li>
             <li><a href="{% url 'mainapp_mlmodel' %}">Models</a></li>
        </ul>

        <div class="tab-content">
            <div id="jobs" class="tab-pane fade in active">
                <h3>Job Details for crawl job <b>{{ job.id }} {{ job.name }}</b></h3>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Field</th>
                            <th>Value</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <b>ID</b>
                            </td>
                            <td>{{ job.id|escape }}</td>
                        </tr>
                         <tr>
                            <td>
                                <b>Name</b>
                            </td>
                            <td>{{ job.name|escape }}</td>
                        </tr>
                         <tr>
                            <td>
                                <b>Domain</b>
                            </td>
                            <td>{{ job.domain|escape }}</td>
                        </tr>
                         <tr>
                            <td>
                                <b>Crawl Type</b>
                            </td>
                            <td>{{ job.get_type_display|escape }}</td>
                        </tr>
                         <tr>
                            <td>
                                <b>Status</b>
                            </td>
                            <td>{{ job.get_status_display|escape }}</td>
                        </tr>
                         <tr>
                            <td>
                                <b>Description</b>
                            </td>
                            <td>{{ job.description|escape }}</td>
                        </tr>
                         <tr>
                            <td>
                                <b>Created On</b>
                            </td>
                            <td>{{ job.created|escape }}</td>
                        </tr>
                         <tr>
                            <td>
                                <b>By User</b>
                            </td>
                            <td>{{ job.user|escape }}</td>
                        </tr>
                        <tr>
                            <td>
                                <b>Storage Location</b>
                            </td>
                            <td><a href="{{ job.storage_location|escape }}" target=_blank>{{ job.storage_location|escape }}</a></td>
                        </tr>
                        <tr>
                            <td>
                                <b>URLs to crawl</b>
                            </td>
                            <td>{{ job.urls|escape }}</td>
                        </tr>
                        <tr>
                            <td>
                                <b>Resources crawled</b>
                            </td>
                            <td>{{ job.docs_collected|escape }}</td>
                        </tr>
						<tr>
                            <td>
                                <b>Resources stored</b>
                            </td>
                            <td>{{ job.docs_uploaded|escape }}</td>
                        </tr>

                        <tr>
                            <td>
                                <b>Collect Everything</b>
                            </td>
                            <td>{{ job.docs_all|escape }}</td>
                        </tr>
                        <tr>
                            <td>
                                <b>Collect HTML</b>
                            </td>
                            <td>{{ job.docs_html|escape }}</td>
                        </tr>
                        <tr>
                            <td>
                                <b>Collect DOCX</b>
                            </td>
                            <td>{{ job.docs_docx|escape }}</td>
                        </tr>
                        <tr>
                            <td>
                                <b>Collect PDF</b>
                            </td>
                            <td>{{ job.docs_pdf|escape }}</td>
                        </tr>
						<tr>
                            <td>
                                <b>Model Name</b>
                            </td>
                            <td>{{ job.model.name|escape }}</td>
                        </tr>
						<tr>
                            <td>
                                <b>Model Classification Labels</b>
                            </td>
                            <td>{{ job.model_labels|escape }}</td>
                        </tr>
						<tr>
                            <td>
                                <b>Crawl Library</b>
                            </td>
                            <td>{{ job.get_crawl_library_display|escape }}</td>
                        </tr>
						<tr>
                            <td>
                                <b>Num Crawl Pages Limit</b>
                            </td>
                            <td>{{ job.num_crawl_pages_limit|escape }}</td>
                        </tr>
						<tr>
                            <td>
                                <b>Crawl Time (milliseconds)</b>
                            </td>
                            <td>{{ job.crawl_time|escape }}</td>
                        </tr>
                        <tr>
                            <td>
                                <a href="{% url 'mainapp_crawlcontents' job_id=job.id %}"><b>Download Crawl Contents</b>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

main/project/templates/main_app/login_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Login
{% endblock %}

{% block content %}

    <form role="form"
          action="{% url 'mainapp_login' %}"
          method="post">
        {% csrf_token %}

        <p>Please sign in.</p>

        {{ form|crispy }}

        <button type="submit" class="btn btn-success">Login</button>
    </form>

{% endblock %}

main/project/templates/main_app/ml_model.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    User: {{ user.username }}
{% endblock %}

{% block content %}
    <h2 class="text-primary">Hello {{ user.username }}</h2>

    <div class="row">
		<ul class="nav nav-tabs">
             <li><a href="{% url 'mainapp_home' %}">Current Jobs</a></li>
             <li><a href="{% url 'mainapp_new_job' %}">New Job</a></li>
			 <li class="active"><a href="{% url 'mainapp_mlmodel' %}">Models</a></li>
        </ul>
        <div class="tab-content">
            <div id="models" class="tab-pane fade in active">
                <h3>Current Models</h3>
                <p>These are all the current models for user {{ user.username }}.</p>
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Model Name</th>
                            <th>Labels</th>
                            <th>Model Creation date</th>
                            <th>Model Storage Location</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for model in models %}
                        <tr>
                            <td>
                                {{ model.name|escape }}
                            </td>
                            <td>
                                {{ model.labels|escape }}
                            </td>
							<td>
                                {{ model.created|escape }}
                            </td>
							<td>
                                {{ model.storage_location|escape }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
				<h3>Add New Model.</h3>
				<p>This is where you can add new model.</p>
                <form id="profile-form" action="{% url 'mainapp_mlmodel' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
						{{ form.as_p }}
						<label> Upload Model </label>
						<input type="file" name="myfile">
                    </div>

                    <div class="form-group">
                        <input type="submit" name="mlmodel-submit" id="mlmodel-submit" tabindex="2"
                        class="form-control btn btn-login btn-primary" value="Add Model">
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

main/project/templates/main_app/new_job.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    User: {{ user.username }}
{% endblock %}

{% block content %}
    <h2 class="text-primary">Hello {{ user.username }}</h2>

    <div class="row">
         <ul class="nav nav-tabs">
             <li><a href="{% url 'mainapp_home' %}">Current Jobs</a></li>
             <li class="active"><a href="{% url 'mainapp_new_job' %}">New Job</a></li>
			 <li><a href="{% url 'mainapp_mlmodel' %}">Models</a></li>
        </ul>

        <div class="tab-content">
            <div id="new_job" class="tab-pane fade in active">
                <h3>New Job</h3>
                <p>Set up a new crawl request.</p>
                <form id="new-job-form" action="{% url 'mainapp_new_job' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.as_p }}
                    </div>

                    <div class="form-group">
                        <input type="submit" name="new-job-submit" id="new-job-submit"
                               class="form-control btn btn-login btn-primary" value="Create job">
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}